version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "dra-pipelines"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-1vp92j7g057py"
s3_prefix = "dra-pipelines"
region = "ap-southeast-1"
capabilities = "CAPABILITY_IAM"
image_repositories = []
