credentials:
  usernames:
    admin:
      email: ND
      name: admin
      password: '$2b$12$NNr8l/RSFSyjzMAtgQdifOzcBpLgjOkv1uZF1yUR0Q7vfSrcQlFya' # To be replaced with hashed password
    pxa:
      email: ND
      name: pxa
      password: '$2b$12$NNr8l/RSFSyjzMAtgQdifOzcBpLgjOkv1uZF1yUR0Q7vfSrcQlFya' # To be replaced with hashed password
cookie:
  expiry_days: 30
  key: some_signature_key
  name: some_cookie_name
preauthorized:
  emails:
  - ND